version: '3.8'

services:
  data-sync:
    image: ${DOCKER_REGISTRY}/${APP_NAME}-sync:${TAG:-latest}
    container_name: legal_dashboard_data_sync_prod
    restart: "no"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      SYNC_HOURS: ${SYNC_HOURS:-24}
      ENV: production
    networks:
      - legal_dashboard_network

  reflex-backend:
    image: ${DOCKER_REGISTRY}/${APP_NAME}-backend:${TAG:-latest}
    container_name: legal_dashboard_backend_prod
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      ENV: production
      API_URL: http://localhost:8000
    ports:
      - "8000:8000"
    networks:
      - legal_dashboard_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  reflex-frontend:
    image: ${DOCKER_REGISTRY}/${APP_NAME}-frontend:${TAG:-latest}
    container_name: legal_dashboard_frontend_prod
    restart: unless-stopped
    depends_on:
      reflex-backend:
        condition: service_healthy
    environment:
      API_URL: ${API_URL:-http://localhost:8000}
    networks:
      - legal_dashboard_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: legal_dashboard_nginx_prod
    restart: unless-stopped
    depends_on:
      reflex-frontend:
        condition: service_healthy
      reflex-backend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/legal_dashboard/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/legal_dashboard/ssl:/etc/nginx/ssl:ro
    networks:
      - legal_dashboard_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  legal_dashboard_network:
    driver: bridge
