services:
  data-sync:
    restart: "no"  # Only run when explicitly triggered
    environment:
      ENV: production
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  reflex-app:
    restart: always
    environment:
      ENV: production
      MONGO_CONNECTION_STRING: mongodb+srv://matiaszulberti:<db_password>@cluster0.pyme8ki.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      REFLEX_BACKEND_HOST: ${REFLEX_BACKEND_HOST:-0.0.0.0}
      REFLEX_FRONTEND_PORT: ${REFLEX_FRONTEND_PORT:-3000}
      REFLEX_BACKEND_PORT: ${REFLEX_BACKEND_PORT:-8000}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    # For production, you might want to disable direct port access
    # and only allow access through nginx reverse proxy
    # Uncomment these lines to disable direct access:
    # ports: []
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '1.5'

# Production network configuration
networks:
  legal_dashboard_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
